'use client'

import { useState } from 'react'
import Image from 'next/image'
import { AlertTriangle, Search, X } from 'lucide-react'
import { demoDocuments, getDemoResult } from '@/lib/demo-data'
import { alerts, evidenceRecords, reports, screenings, watchlist } from '@/lib/data'
import { PageHeader } from '@/components/page-header'
import { RiskBadge } from '@/components/risk-badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'

function Note() { return <p className="text-xs font-medium uppercase tracking-[.16em] text-primary">Controlled local data</p> }
const demoRows = demoDocuments.map((document) => ({ ...document, result: getDemoResult(document.filename) }))

export function HistoryDemoPage() { return <><PageHeader title="Screening History" description="Review previous controlled screenings." /><Note /><Card><CardContent className="p-0"><div className="divide-y">{demoRows.map((document) => { const result = document.result; if (!result) return null; return <a key={document.filename} href={`/screening/${encodeURIComponent(`demo:${document.filename}`)}`} className="grid gap-2 px-5 py-4 hover:bg-accent lg:grid-cols-[1.1fr_1fr_.7fr_.8fr_.6fr_1fr_auto] lg:items-center"><span className="font-mono text-sm">{result.screening.id}</span><span className="flex items-center gap-3 text-sm"><Image src={`/dataset/${document.filename}`} alt="" width={48} height={32} className="h-8 w-12 rounded object-cover" />{document.label}</span><span className="text-sm text-muted-foreground">{document.type}</span><RiskBadge level={result.result.level} /><span className="font-mono text-sm">{result.screening.score}/100</span><span className="text-sm text-muted-foreground">Current session</span><span className="text-sm text-primary">View Result</span></a> })}{screenings.slice(0, 4).map((screening) => <a key={screening.id} href={`/screening/${screening.id}`} className="grid gap-2 px-5 py-4 hover:bg-accent lg:grid-cols-[1.1fr_1fr_.7fr_.8fr_.6fr_1fr_auto] lg:items-center"><span className="font-mono text-sm">{screening.id}</span><span className="text-sm">{screening.traveler}</span><span className="text-sm text-muted-foreground">{screening.documentType}</span><RiskBadge level={screening.risk} /><span className="font-mono text-sm">{screening.score}/100</span><span className="text-sm text-muted-foreground">{screening.time}</span><span className="text-sm text-primary">View Result</span></a>)}</div></CardContent></Card></> }

export function IntelligenceDemoPage() { return <><PageHeader title="Identity Intelligence" description="Review identity consistency and document relationships." /><Note /><div className="grid gap-4 md:grid-cols-3">{[['Face Match Score', '96%', 'High confidence'], ['Duplicate Identities', '01', 'Review required'], ['Previous Screenings', '04', 'Across records']].map(([label, value, detail]) => <Card key={label}><CardContent className="p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-3 font-mono text-3xl font-semibold">{value}</p><p className="mt-1 text-sm text-muted-foreground">{detail}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Identity Match Overview</CardTitle><CardDescription>Local identity profile associated with the selected screening subject.</CardDescription></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Name', 'DEMO HOLDER'], ['Document Number', 'G9850821'], ['Nationality', 'India'], ['Date of Birth', '01 Jan 1990'], ['Previous Screening Count', '4']].map(([label, value]) => <div key={label} className="rounded-lg border border-border/60 p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-sm font-medium">{value}</p></div>)}</div></CardContent></Card></> }

export function WatchlistDemoPage() { const [query, setQuery] = useState(''); const filtered = watchlist.filter((entry) => `${entry.name} ${entry.documentNumber} ${entry.nationality} ${entry.reason}`.toLowerCase().includes(query.toLowerCase())); return <><PageHeader title="Watchlist" description="Search local watchlist records." /><Note /><Card><CardContent className="p-5"><div className="relative max-w-xl"><Search className="absolute top-2.5 left-3 size-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, document number, or reason" className="pl-9" /></div></CardContent></Card><div className="grid gap-3">{filtered.map((entry) => <Card key={entry.id}><CardContent className="flex flex-col gap-3 p-5 md:flex-row md:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-3"><span className="font-mono text-xs text-muted-foreground">{entry.id}</span><span className="font-medium">{entry.name}</span></div><p className="mt-1 text-sm text-muted-foreground">{entry.documentNumber} · {entry.nationality} · {entry.reason}</p></div><span className="rounded-full bg-destructive/10 px-3 py-1 text-xs font-medium text-destructive">{entry.category}</span><span className="text-sm text-muted-foreground">{entry.added}</span></CardContent></Card>)}</div></> }

export function AlertsDemoPage() { const [items, setItems] = useState(alerts); return <><PageHeader title="Alerts" description="Review and acknowledge screening alerts." /><Note /><div className="grid gap-3">{items.map((alert) => <Card key={alert.id} className={cn(alert.status === 'Resolved' && 'opacity-60')}><CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-center"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-destructive/10 text-destructive"><AlertTriangle className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-muted-foreground">{alert.id}</span><span className="font-medium">{alert.reason}</span></div><p className="mt-1 text-sm text-muted-foreground">{alert.screeningId} · {alert.checkpoint} · {alert.time}</p></div><RiskBadge level={alert.severity} /><Button size="sm" variant="outline" disabled={alert.status === 'Resolved'} onClick={() => setItems((current) => current.map((item) => item.id === alert.id ? { ...item, status: 'Resolved' } : item))}>{alert.status === 'Resolved' ? 'Reviewed' : 'Mark as reviewed'}</Button></CardContent></Card>)}</div></> }

export function AnalyticsDemoPage() { const counts = [['Verified', 8, 'bg-success'], ['Suspicious', 3, 'bg-warning'], ['High Risk', 5, 'bg-destructive']] as const; return <><PageHeader title="Analytics" description="A lightweight view of screening activity." /><Note /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Total Screenings', '16'], ['Verified', '50%'], ['Suspicious', '19%'], ['High Risk', '31%']].map(([label, value]) => <Card key={label}><CardContent className="p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-3 font-mono text-3xl font-semibold">{value}</p></CardContent></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Risk Distribution</CardTitle></CardHeader><CardContent className="space-y-5">{counts.map(([label, value, color]) => <div key={label}><div className="mb-2 flex justify-between text-sm"><span>{label}</span><span className="font-mono">{value}</span></div><div className="h-3 rounded-full bg-muted"><div className={cn('h-3 rounded-full', color)} style={{ width: `${value / 16 * 100}%` }} /></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Documents by Type</CardTitle></CardHeader><CardContent className="space-y-4">{[['Passports', '10'], ['Visas', '4'], ['Other travel documents', '2']].map(([label, value]) => <div key={label} className="flex justify-between border-b border-border/60 pb-3 text-sm last:border-0"><span>{label}</span><span className="font-mono text-muted-foreground">{value}</span></div>)}</CardContent></Card></div></> }

export function AuditDemoPage() { return <><PageHeader title="Blockchain Audit" description="Evidence records are simulated locally." /><Note /><Card><CardHeader><CardTitle>Evidence Ledger Timeline</CardTitle><CardDescription>Simulated evidence ledger for document review.</CardDescription></CardHeader><CardContent className="space-y-3">{evidenceRecords.slice(0, 4).map((record) => <div key={record.screeningId} className="grid gap-3 rounded-lg border border-border/60 p-4 text-sm md:grid-cols-6 md:items-center"><span className="font-mono">{record.screeningId}</span><span><span className="block text-xs text-muted-foreground">Document Hash</span>{record.documentHash}</span><span><span className="block text-xs text-muted-foreground">Evidence Hash</span>{record.evidenceHash}</span><span><span className="block text-xs text-muted-foreground">Transaction ID</span>{record.txId}</span><span><span className="block text-xs text-muted-foreground">Block Number</span>{record.block}</span><span className="text-success">CONFIRMED · DEMO LEDGER</span></div>)}</CardContent></Card></> }

export function ReportsDemoPage() { const [selected, setSelected] = useState<typeof reports[number] | null>(null); return <><PageHeader title="Reports" description="Open printable summaries for previous screenings." /><Note /><Card><CardContent className="p-0"><div className="divide-y">{reports.map((report) => { const screening = screenings.find((item) => item.id === report.screeningId); return <div key={report.id} className="flex flex-col gap-3 px-5 py-4 md:flex-row md:items-center"><div className="flex-1"><p className="font-mono text-sm">{report.id} · {report.screeningId}</p><p className="text-sm text-muted-foreground">{screening?.traveler ?? 'Screening record'} · {report.date}</p></div><RiskBadge level={report.risk} /><Button size="sm" variant="outline" onClick={() => setSelected(report)}>View Report</Button></div> })}</div></CardContent></Card>{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4 backdrop-blur-sm"><Card className="w-full max-w-lg"><CardHeader className="flex flex-row items-start justify-between"><div><CardTitle>Screening Report</CardTitle><CardDescription>{selected.id} · {selected.screeningId}</CardDescription></div><Button size="icon" variant="ghost" aria-label="Close report" onClick={() => setSelected(null)}><X /></Button></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">This report is generated from the local controlled dataset.</p><div className="grid grid-cols-2 gap-3 text-sm"><span className="text-muted-foreground">Verdict</span><RiskBadge level={selected.risk} /><span className="text-muted-foreground">Generated</span><span>{selected.date}</span><span className="text-muted-foreground">Status</span><span>{selected.status}</span></div><Button className="w-full" onClick={() => window.print()}>Print Report</Button></CardContent></Card></div>}</> }

export function SettingsDemoPage() { const [speed, setSpeed] = useState('Standard'); const [notifications, setNotifications] = useState(true); const setTheme = (theme: 'light' | 'dark') => { localStorage.setItem('border-shield-theme', theme); window.dispatchEvent(new CustomEvent('border-shield-theme', { detail: theme })) }; return <><PageHeader title="Settings" description="Configure the local workstation." /><Note /><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Appearance</CardTitle><CardDescription>Theme changes apply across every page.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3"><Button variant="outline" onClick={() => setTheme('light')}>Light Theme</Button><Button onClick={() => setTheme('dark')}>Dark Theme</Button></CardContent></Card><Card><CardHeader><CardTitle>Workspace Controls</CardTitle><CardDescription>Local presentation settings.</CardDescription></CardHeader><CardContent className="space-y-4"><label className="flex items-center justify-between text-sm">Prototype Mode <span className="rounded-full bg-success/10 px-2 py-1 text-xs text-success">ON</span></label><label className="flex items-center justify-between gap-4 text-sm">Animation Speed <select value={speed} onChange={(event) => setSpeed(event.target.value)} className="rounded-md border border-input bg-background px-3 py-2"><option>Relaxed</option><option>Standard</option><option>Fast</option></select></label><label className="flex items-center justify-between text-sm">Notifications <input type="checkbox" checked={notifications} onChange={(event) => setNotifications(event.target.checked)} /></label><div className="flex items-center justify-between text-sm"><span>Language</span><span className="text-muted-foreground">English</span></div></CardContent></Card></div></> }
